import React, {
  FC, Context, createContext, useState,
} from 'react';
import { ShowsResults, ShowDetails, Show } from '../ts/showInterfaces';

export const ShowsContext: Context<any> = createContext({});

export const ShowsProvider: FC = ({ children }) => {
  const [trending, setTrending] = useState<ShowsResults>();
  const [favorites, setFavorites] = useState<ShowDetails[]>();
  const [page, setPage] = useState(1);
  const [searchResults, setSearchResults] = useState<Show[]>(
    [
      {
        backdrop_path: '/nqzBAMnuMI0xuwtdlEcxcQafyXY.jpg',
        first_air_date: '2004-09-22',
        genre_ids: [
          10759,
          9648,
        ],
        id: 4607,
        name: 'Lost',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Lost',
        overview: 'Stripped of everything, the survivors of a horrific plane crash  must work together to stay alive. But the island holds many secrets.',
        popularity: 131.511,
        poster_path: '/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg',
        vote_average: 7.9,
        vote_count: 2337,
      },
      {
        backdrop_path: '/9jlwGGx9zTkEV5mnuyQXDTUMCw3.jpg',
        first_air_date: '2010-09-12',
        genre_ids: [
          10765,
          18,
        ],
        id: 33852,
        name: 'Lost Girl',
        origin_country: [
          'CA',
        ],
        original_language: 'en',
        original_name: 'Lost Girl',
        overview: 'The gorgeous and charismatic Bo is a supernatural being called a succubus who feeds on the energy of humans, sometimes with fatal results. Refusing to embrace her supernatural clan and its rigid hierarchy, Bo is a renegade who takes up the fight for the underdog while searching for the truth about her own mysterious origins.',
        popularity: 42.486,
        poster_path: '/jE6sqorxIyVU55VhDbz7NbqxZlV.jpg',
        vote_average: 7.6,
        vote_count: 261,
      },
      {
        backdrop_path: '/bi7YzaN4tozvOeNNP7P6erzFcpr.jpg',
        first_air_date: '2018-04-13',
        genre_ids: [
          10765,
          10759,
          18,
        ],
        id: 75758,
        name: 'Lost in Space',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Lost in Space',
        overview: "After crash-landing on an alien planet, the Robinson family fights against all odds to survive and escape. But they're surrounded by hidden dangers.",
        popularity: 44.009,
        poster_path: '/y8NJnTXzb4rio9uvVYFVrXEMofU.jpg',
        vote_average: 7.5,
        vote_count: 814,
      },
      {
        backdrop_path: '/fyrAObqU9IBWTu6CwRx7fwA7pFV.jpg',
        first_air_date: '1965-09-15',
        genre_ids: [
          10765,
        ],
        id: 3051,
        name: 'Lost in Space',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Lost in Space',
        overview: "The space family Robinson is sent on a five-year mission to find a new planet to colonise. The voyage is sabotaged time and again by an inept stowaway, Dr. Zachary Smith. The family's spaceship, Jupiter II, also carries a friendly robot who endures an endless stream of abuse from Dr. Smith, but is a trusted companion of young Will Robinson",
        popularity: 32.937,
        poster_path: '/dGhtCpYZutuso2P3GKWnQnqwhSi.jpg',
        vote_average: 7.1,
        vote_count: 56,
      },
      {
        backdrop_path: '/7NgXdhIE0v357kAiUcgYN2F4cqg.jpg',
        first_air_date: '2017-12-08',
        genre_ids: [
          16,
          18,
          10759,
        ],
        id: 75875,
        name: 'Attack on Titan: Lost Girls',
        origin_country: [
          'JP',
        ],
        original_language: 'ja',
        original_name: '進撃の巨人 LOST GIRLS',
        overview: 'Shingeki no Kyojin OVA that is bundled with manga volumes 24, 25, and 26. Several hundred years ago, mankind was nearly extinct because of the Titans. The Titans are big, have no intellect, hate people, and worst of all, they think of humans as food. The survivors of the humans built a very high wall to protect them from the Titans.',
        popularity: 77.122,
        poster_path: '/3mtcwmGAwjNrIlLveYBKhLC3Fqh.jpg',
        vote_average: 8.5,
        vote_count: 13,
      },
      {
        backdrop_path: '/7ggAjuO3g4AMt3p1ZsGeBNqLMsb.jpg',
        first_air_date: '1999-04-03',
        genre_ids: [
          10759,
        ],
        id: 896,
        name: 'The Lost World',
        origin_country: [
          'AU',
        ],
        original_language: 'en',
        original_name: 'The Lost World',
        overview: 'Early 20th-century adventurers find themselves fighting for survival after their hot-air balloon crashes into a remote part of the Amazon, stranding them on a prehistoric plateau.',
        popularity: 19.363,
        poster_path: '/whA1PLf8nslT3R7kSvCssTCCUba.jpg',
        vote_average: 7,
        vote_count: 50,
      },
      {
        backdrop_path: null,
        first_air_date: '2018-08-17',
        genre_ids: [
          99,
        ],
        id: 122805,
        name: "Dr. Lava's Lost Pokemon",
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: "Dr. Lava's Lost Pokemon",
        overview: 'Lost Pokemon History: scrapped Pokemon designs, cut content, and Japan-exclusive content.',
        popularity: 16.794,
        poster_path: null,
        vote_average: 8,
        vote_count: 1,
      },
      {
        backdrop_path: '/a4EEflc6pqP7ZT3yfuDMYV3sfH8.jpg',
        first_air_date: '2006-12-11',
        genre_ids: [
          9648,
          10765,
        ],
        id: 3868,
        name: 'The Lost Room',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'The Lost Room',
        overview: 'A detective investigates a mysterious motel room, which acts as a portal to an alternate universe.',
        popularity: 9.579,
        poster_path: '/ixfo1ysvboBxYehdDDC9D0T3Q33.jpg',
        vote_average: 7.8,
        vote_count: 279,
      },
      {
        backdrop_path: '/wci4coPpl3DRnXCiLxeGD5Rc4Kc.jpg',
        first_air_date: '2009-06-24',
        genre_ids: [
          16,
          10759,
        ],
        id: 61389,
        name: 'Saint Seiya The Lost Canvas',
        origin_country: [
          'JP',
        ],
        original_language: 'ja',
        original_name: '聖闘士星矢 THE LOST CANVAS 冥王神話',
        overview: "An orphan known as Tenma becomes one of Athena's 88 warriors known as Saints and finds himself in a war fighting against his best friend Alone who is revealed to be the reincarnation of Athena's biggest enemy, the God Hades.",
        popularity: 50.558,
        poster_path: '/2CLmvKdPVe9DirsAM51OTvMzmvh.jpg',
        vote_average: 8,
        vote_count: 386,
      },
      {
        backdrop_path: null,
        first_air_date: '1984-09-22',
        genre_ids: [
          18,
        ],
        id: 13566,
        name: 'Finder of Lost Loves',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Finder of Lost Loves',
        overview: 'Finder of Lost Loves is an American drama series aired by the ABC network during the 1984-1985 season.',
        popularity: 13.207,
        poster_path: null,
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: '/pSQdbgTnFaBonBRqnZrmoXOFWE2.jpg',
        first_air_date: '2008-09-03',
        genre_ids: [
          18,
        ],
        id: 15129,
        name: 'Lost in Austen',
        origin_country: [
          'GB',
        ],
        original_language: 'en',
        original_name: 'Lost in Austen',
        overview: 'Modern Amanda enters through a portal in her bathroom, to join the Bennet family and affect events disastrously.',
        popularity: 6.418,
        poster_path: '/d6VgUAO3JGvohm2Ij9vMzgfCvDa.jpg',
        vote_average: 7.3,
        vote_count: 71,
      },
      {
        backdrop_path: '/xRVdFfvErr9VyVdaaRdY2MsR5Js.jpg',
        first_air_date: '2015-06-26',
        genre_ids: [
          16,
          10751,
          10765,
          10762,
        ],
        id: 63054,
        name: 'Lost in Oz',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Lost in Oz',
        overview: "When 12-year-old Dorothy Gale discovers her mother's mysterious journal in her Kansas home, she and her dog, Toto, are transported into a bustling, modern Emerald City. Disoriented and determined to get home, Dorothy embarks on an epic journey with West, a young witch, and Ojo, a giant Munchkin, to seek the magic she needs - as Oz faces its greatest magic crisis. Based on L. Frank Baum's books.",
        popularity: 7.44,
        poster_path: '/bYPm31BjQed8fqbly7BFPjsOjLH.jpg',
        vote_average: 8,
        vote_count: 10,
      },
      {
        backdrop_path: '/dNRr2e8B6cAjU3YhS5qbEVo2LZl.jpg',
        first_air_date: '2020-04-13',
        genre_ids: [
          18,
          9648,
        ],
        id: 96195,
        name: 'Paradise Lost',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Paradise Lost',
        overview: 'A psychiatrist moves with her family from California to her husband’s hometown in Mississippi only to uncover shameful secrets that irrevocably change the lives of everyone involved.',
        popularity: 3.946,
        poster_path: '/ddmZnaxFkAl2yTCjiaHnxsaydtT.jpg',
        vote_average: 10,
        vote_count: 1,
      },
      {
        backdrop_path: null,
        first_air_date: '1986-10-24',
        genre_ids: [],
        id: 13698,
        name: 'Lost Empires',
        origin_country: [
          'GB',
        ],
        original_language: 'en',
        original_name: 'Lost Empires',
        overview: "Lost Empires is a 1986 television adaptation of J. B. Priestley's novel of the same name, and starred Colin Firth, John Castle and Laurence Olivier. Produced by Granada Television, it was shown as a serial, and premiered on the UK's ITV network in October and November 1986.",
        popularity: 3.624,
        poster_path: null,
        vote_average: 5,
        vote_count: 1,
      },
      {
        backdrop_path: '/61AZhYnjayWHld2ocdYtX9k6PKH.jpg',
        first_air_date: '2021-03-15',
        genre_ids: [
          99,
        ],
        id: 118815,
        name: 'The Lost Pirate Kingdom',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'The Lost Pirate Kingdom',
        overview: "The real-life pirates of the Caribbean violently plunder the world's riches and form a surprisingly egalitarian republic in this documentary series.",
        popularity: 5.47,
        poster_path: '/gQZpVysbT5FGYVYrsjuwQa2XIay.jpg',
        vote_average: 7.8,
        vote_count: 21,
      },
      {
        backdrop_path: '/dw3Uk4XY886L3kEzMnjZjBP3b0d.jpg',
        first_air_date: '2007-11-05',
        genre_ids: [],
        id: 125885,
        name: 'Lost: Missing Pieces',
        origin_country: [],
        original_language: 'en',
        original_name: 'Lost: Missing Pieces',
        overview: "13 never-before-seen stories taken from the 'Lost' Flashbacks. The creative team is the same and the stories give more clues about the past days of the island characters.",
        popularity: 3.787,
        poster_path: '/nlkZa8Vqznf4P4AkFY1ObjUGapg.jpg',
        vote_average: 6,
        vote_count: 3,
      },
      {
        backdrop_path: '/lcvwthqQv6PTuLc4CWnEwa2uKYC.jpg',
        first_air_date: '2015-12-11',
        genre_ids: [
          10751,
        ],
        id: 66260,
        name: 'Lost & Found Music Studios',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Lost & Found Music Studios',
        overview: '',
        popularity: 3.805,
        poster_path: '/1VaaYENYc8SHsyeudATNZVVfzyx.jpg',
        vote_average: 8.8,
        vote_count: 17,
      },
      {
        backdrop_path: '/kJB50LyeILumAAhSJetPtpiHLmD.jpg',
        first_air_date: '1974-09-07',
        genre_ids: [
          10759,
          10765,
          10751,
        ],
        id: 2177,
        name: 'Land of the Lost',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Land of the Lost',
        overview: 'Rick Marshall and his children Will and Holly were on a weekend expedition rafting trough a river when an enormous earthquake diverts them to an eclectic alien world inhabited by dinosaurs, chimpanzee-like cavemen called Pakuni, and aggressive, humanoid creatures called Sleestak.',
        popularity: 3.605,
        poster_path: '/eMMYJ3ozsr2zXwnZbSkKRxJOyyr.jpg',
        vote_average: 7.7,
        vote_count: 24,
      },
      {
        backdrop_path: null,
        first_air_date: '1991-09-07',
        genre_ids: [
          35,
          10759,
          10762,
          10765,
        ],
        id: 11645,
        name: 'Land of the Lost',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'Land of the Lost',
        overview: "Land of the Lost is a half-hour Saturday-morning children's series that debuted on ABC in the fall of 1991. Re-runs were later picked up by Nickelodeon. Tiger Toys received the license to produce a toyline based on the series, which included regular and \"talking\" action figures, several dinosaurs and playsets, an electronic Crystal Sword, as well as an electronic LCD game and a board game.\n\nThe Porter family, Tom, Kevin, and Annie get sucked into a prehistoric alternative world while taking a family vacation. The Porters build a tree house, hook up with a few locals, Tasha - orphaned, an extra smart dinosaur, Stink - a monkey man, and Christa - another human who has lived in the Land of the Lost since she was a little girl. The Porters must deal with living with dinosaurs and avoiding the evil advanced Sleestaks.",
        popularity: 3.533,
        poster_path: '/hW4Jt47sDXOY9DmTbL84318dFbU.jpg',
        vote_average: 7,
        vote_count: 10,
      },
      {
        backdrop_path: null,
        first_air_date: '2001-03-11',
        genre_ids: [
          10759,
          10765,
        ],
        id: 45613,
        name: 'The Lost Empire',
        origin_country: [
          'US',
        ],
        original_language: 'en',
        original_name: 'The Lost Empire',
        overview: 'A contemporary take on the classic Chinese novel Journey to the West.',
        popularity: 3.159,
        poster_path: '/cPsBlGhlFbeUd6G7a4Tb8w6O7Mo.jpg',
        vote_average: 4.6,
        vote_count: 17,
      },
    ],
  );

  return (
    <ShowsContext.Provider
      value={{
        trending,
        setTrending,
        favorites,
        setFavorites,
        page,
        setPage,
        searchResults,
        setSearchResults,
      }}
    >
      {children}
    </ShowsContext.Provider>
  );
};
